#!/bin/sh
STASH_NAME="pre-commit-$(date +%s)"
git stash save -q --keep-index --include-untracked $STASH_NAME

RESULT="$(./run.sh)"

: '
STASHES=$(git stash list)
if [[ $STASHES == "$STASH_NAME" ]]; then
  git stash pop -q 
fi
'
git stash pop -q --index 0

if [ "$RESULT" = "0" ]; then
 exit 0
fi
echo $RESULT
exit 1
