#!/bin/sh
STASH_NAME="pre-commit-$(date +%s)"
git stash save -q --keep-index --include-untracked $STASH_NAME

BASEDIR=$(dirname "$0")
RESULT=$(. "$PWD"/run_tests.sh)
STATUS=$?
: '
STASHES=$(git stash list)
if [[ $STASHES == "$STASH_NAME" ]]; then
  git stash pop -q 
fi
'
git stash pop -q --index 0
echo "status: '$STATUS'"
if [ "$STATUS" != "0" ]; then
 echo $RESULT
fi
exit $STATUS
